name: Sync Notion to README

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "0 6 * * *"   # runs daily at 6 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install @notionhq/client

      - name: Run fetch script
        run: node fetch-notion.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "🔄 Sync Notion → README"
          git push
