name: sync

on:
  workflow_dispatch: # run manually
  schedule:
    - cron: "0 * * * *" # optional hourly sync

permissions:
  contents: write   # 👈 allow push

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install @notionhq/client

      - name: Run fetch script
        run: node fetch-notion.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📖 Sync Notion → README" || echo "No changes to commit"
          git push
